### ISSUE TITLE
mid-bar repeats

### ISSUE THREAD

**Issue by minamouse** [music-encoding/sibmei#34]
Mid-bar repeats in sibelius end up on the closest barline in the mei files, instead of in the bar. [Here](https://github.com/DDMAL/mei-test-set/blob/develop/MEI-test-set/MEI/repeats/mid-bar-repeat.mei) for example. In these cases, `<barLine/>` should be used in the middle of the measure.

**Comment by pe-ro** [comment]
<barLine> is not the right way to approach this. From the Guidelines --

"This element is provided for repertoires, such as mensural notation, that lack measures. Because the barLine element's attributes, from which the logical and visual characteristics of the bar line can be discerned, largely duplicate those of measure, the use of barLine is not necessary within measure elements in CMN."

The intention is to avoid so-called "mid-measure" bar lines by creating two incomplete measures instead.

__________________________
Perry Roland
Music Library
University of Virginia
P. O. Box 400175
Charlottesville, VA 22904
434-982-2702 (w)
pdr4h (at) virginia (dot) edu
________________________________

**Comment by mborsodi** [comment]
Oh ok, my mistake.
