### ISSUE TITLE
accid vs accid.ges

### ISSUE THREAD

**Issue by lpugin** [music-encoding/sibmei#38]
The output in SibMEI does not take into account the key signature and add an accid attribute to all notes even if it is given in the key signature. For example, in G-major, all F (e.g., F-sharp) have an accid="s". F-natural have no accid attribute.

I am not sure the guidelines are very clear how to use accid and accid.ges, but this does not seems to be compliant with what we have in the MEI examples. The practice in all the examples I looked at is to use the accid attribute to encode what appears in the score and accid.ges for how it sounds. So in G-major, F-sharp have an accid.ges="s" but no accid. F-natural have an accid="n" (accid.ges is not necessary, I guess) and notes with accidental (sharp) not in the key signature have both accid="s" and accid.ges="s". (Only the first note in the measure will have and accid="s").

**Comment by pe-ro** [comment]
The use of accid.ges is optional, but when it’s missing the sounded effect of an accidental must be implied by downstream processors.  In other words, SibMEI is behaving properly, but the encoding it produces is not as explicit as it could be.  For most CMN cases, the use of accid.ges should follow the pattern Laurent describes.  However, there are cases (primarily in twelve-tone compositions) where an accidental affects only the immediately following note.

**Comment by lpugin** [comment]
I am not sure I understand. In current SibMEI output, we can say that accid is the same as accid.ges and that we would expect to have an accid.vis when the appearance differs from CNM behavior (CNM behavior being that the accid from key sig should not be displayed, and accid not from the key sig should be displayed only the first time in the measure). 

The example are doing somehow the opposite, that is accid is the same as accid.vis, and accid.ges is provided for processing (sound) without having to look at the key signature or at previous notes in the measure.

**Comment by lpugin** [comment]
PS the documentation for accid reads "captures a written accidental", so it seems that the MEI examples are correct.

**Comment by pe-ro** [comment]
I haven’t seen any actual output from SibMEI, so I’m somewhat “in the dark” here.

Your description is accurate – accid and accid.vis are, in effect, the same thing since there is, in fact, no accid.vis attribute.  The accid attribute records what one sees on the page.  So far, so good.

In CMN, accid is the same as accid.ges for those places where it (accid) is specified.  That said, I don’t understand your point in your first paragraph.  It’s Monday morning, break it down for me, slowly.  ☺

**Comment by karend27** [comment]
Hi,
Just trying to understand this issue and the current status. I ran a file I generated with SibMEI through verovio and have this issue - notes that should be flat according to key signature are displaying with natural signs (see attached jpeg of showing measures 9-11). The issue is in measure 11 and the XML is pasted below. Is the issue that <accid> is in the code as a separate element rather than as an accid.ges attribute of <note>?

<measure xml:id="m-229" n="11">
                        <staff xml:id="m-230" n="1">
                            <layer xml:id="m-231" n="1">
                                <note xml:id="m-232" dur="breve" dur.ges="2048p" layer="1" oct="4" pname="b" pnum="70" staff="1" stem.dir="down">
                                    <accid xml:id="m-233" accid="f"/>
                                    <verse xml:id="m-256" n="1">
                                        <syl xml:id="m-257" wordpos="i">tri</syl>
                                    </verse>
                                </note>
                                <note xml:id="m-234" dur="1" dur.ges="1024p" layer="1" oct="4" pname="a" pnum="69" staff="1" stem.dir="up">
                                    <verse xml:id="m-258" n="1">
                                        <syl xml:id="m-259" wordpos="m">ni</syl>
                                    </verse>
                                </note>
                                <note xml:id="m-236" artic="stacc" dur="1" dur.ges="1024p" layer="1" oct="4" pname="g" pnum="67" staff="1" stem.dir="up">
                                    <verse xml:id="m-260" n="1">
                                        <syl xml:id="m-261" wordpos="m">ta</syl>
                                    </verse>
                                </note>
                            </layer>
                        </staff>
                        <staff xml:id="m-237" n="2">
                            <layer xml:id="m-238" n="1">
                                <rest xml:id="m-239" dur="long" dur.ges="4096p"/>
                            </layer>
                        </staff>
                        <staff xml:id="m-240" n="3">
                            <layer xml:id="m-241" n="1">
                                **<note xml:id="m-242" dur="long" dur.ges="4096p" layer="1" oct="3" oct.ges="2" pname="b" pnum="46" staff="3" stem.dir="down">
                                    <accid xml:id="m-243" accid.ges="f"/>**
                                </note>
                            </layer>
                        </staff>
                        <tie xml:id="m-244" endid="#m-273" startid="#m-242"/>
                        <fermata xml:id="m-235" form="norm" layer="1" shape="angular" staff="1" startid="#m-234"/>
                    </measure>

**Comment by karend27** [comment]
![screen shot 2016-04-29 at 09 37 48](https://cloud.githubusercontent.com/assets/11195203/14917917/5cde92a2-0def-11e6-9c66-6e62ceed8e25.png)

**Comment by lpugin** [comment]
This is a bug in Verovio when using accid elements (and not accid attributes)

**Comment by karend27** [comment]
Ok - great, thanks! So our MEI files are okay.

**Comment by davidrizo** [comment]
Hi, 
then, currently, if I understand well both this discussion and the other Craig has linked...

For this key signature:
`<staffDef n="1" lines="5" clef.line="2" clef.shape="G" meter.sym="common" key.sig="2f" label="Soprano">`
....
In this sequence, this is what should be printed and played given the MEI encoding:
`<note pname="b" dur="4" oct="3" accid.ges="f"/>`
`<!-- sound expected: Bb, written B without a flat -->`

`<note pname="e" dur="4" oct="3"/> `
`<!-- sound expected Eb because accid.ges is optional, written E without a flat because it is in the key signature-->`

`<note pname="b" dur="4" oct="3" accid="n"/> `
`<!-- sound expected natural B, written B with a natural -->`

`<note pname="b" dur="4" oct="3" accid="f"/> `
`<!-- sound expected flat B, written B with a flat --> `                    
                  
Thanks !!

**Comment by th-we** [comment]
Sibmei now uses the `<accid>` element with `@accid` and `@accid.ges`, depending on written or just sounding. If there's anything still wrong, feel free to re-open this issue.
