### ISSUE TITLE
corruption of XML in export

### ISSUE THREAD

**Issue by karend27** [music-encoding/sibmei#92]
Hi - we're having an issue with corruption of the XML in the SibMEI export - this is a little hard to explain because I don't totally understand what's happening. I'll try to step through it and post some screenshots. We run the SibMEI export through a series of three different scripts for use on our website. First we transform the SibMEI to mei mensural using this script:
https://github.com/DDMAL/CMN-MEI_to_MensuralMEI_Translator
Then we run a script to add metadata to both the mei file from the SibMEI export, and the mensural MEI file from MEI_to_MensuralMEI translator.

When we run this script we get an error on the mei file from the SibMEI export, but not on the one that has been run through the translator.

The error is: An Invalid XML character(Unicode: 0x0) was found in the element content of the document error
and when you open it in oxygen you can see there are some sort of incorrect characters before the very first tag so obviously the XML is not valid.
An online forum suggested opening the file in a hex editor and you can see here - pasted images - in the mensural file that looks fine - but in the one coming from SibMEI there are a bunch of dots in between every character.

What's weird is that the one that is run through the MEI translator is the invalid file but it comes out of that process as valid. 

Any ideas about what is happening in the sibMEI export and why it would be getting corrupted like this?

I'm also attaching zips of both files.

<img width="1007" alt="screen shot 2018-07-04 at 13 42 16" src="https://user-images.githubusercontent.com/11195203/42277693-255de2a0-7f90-11e8-8c3f-2597cecc16fd.png">
<img width="1006" alt="screen shot 2018-07-04 at 13 42 24" src="https://user-images.githubusercontent.com/11195203/42277694-268d6394-7f90-11e8-8ce6-2277aa21ed1b.png">
[Fauv.zip](https://github.com/music-encoding/sibmei/files/2163235/Fauv.zip)

**Comment by karend27** [comment]
@martha-thomae @th-we

**Comment by ahankinson** [comment]
This is a limitation of Sibelius. It can only produce output in either ASCII (which means all accents, etc. are corrupted) or UTF-16. This contains a Byte Order Mark (BOM). 

You're getting this error because you're telling your XML parser to open it in UTF-8, and it's failing on trying to parse the BOM. If you tell it to open it in UTF-16, it should be fine.

**Comment by karend27** [comment]
Thanks Andrew for the quick reply. We'll try that. It looks like when the file comes out of the SibMEI export it has <?xml version="1.0" encoding="UTF-8"?> as the first tag; but after it comes out of the Mensural translator it has <?xml version="1.0" encoding="UTF-8"?>. 

Is this something that changed with a more recent version of the plugin? It wasn't a problem we had before but I updated my SibMEI plugin last week.

Thanks!

**Comment by ahankinson** [comment]
No, it's been a (common, persistent, unfortunate) problem from the start. There's nothing to be done about it. 😢 

The `<?xml>` tag declaration does not necessarily reflect the *actual* encoding of the file. It's possible to have `<?xml version="1.0" encoding="UTF-8"?>` and the file actually be encoded in UTF-16. The declaration is just a hint to say what it's supposed to be, but, just like I can say I'm the greatest programmer in the world, the actual reality can be quite different.

The difference is that UTF-16 uses 2 bytes / 16 bits per character, while UTF-8 uses 1 byte / 8 bits. In your hex editor you can see this extra byte as a '.' character -- since it doesn't need 2 bytes to encode a letter "A", for example, it sets that byte to 'null'; notice all the "00"s in the UTF-16 version. 

This article explains a bit more:

https://www.quora.com/What-is-the-difference-between-UTF-8-and-UTF-16

**Comment by karend27** [comment]
Ok thanks - that's very helpful, and we won't get distracted by what's in the declaration.
